/**
 * GitHub API client for image storage and synchronization.
 * Handles repository management and file operations.
 */

const GITHUB_API_BASE = "https://api.github.com";
const REPO_NAME = "imagegate-images";
const REPO_DESCRIPTION = "Images generated by ImageGate - AI Image Generation Service";

interface GitHubFileResponse {
  content: {
    name: string;
    path: string;
    sha: string;
    size: number;
    download_url: string;
    html_url: string;
  };
  commit: {
    sha: string;
    message: string;
  };
}

interface GitHubRepoResponse {
  id: number;
  name: string;
  full_name: string;
  private: boolean;
  html_url: string;
  description: string;
}

/**
 * Make an authenticated request to GitHub API
 */
async function githubFetch(
  endpoint: string,
  accessToken: string,
  options: RequestInit = {}
): Promise<Response> {
  const url = endpoint.startsWith("http") ? endpoint : `${GITHUB_API_BASE}${endpoint}`;

  const response = await fetch(url, {
    ...options,
    headers: {
      Accept: "application/vnd.github.v3+json",
      Authorization: `Bearer ${accessToken}`,
      "X-GitHub-Api-Version": "2022-11-28",
      ...options.headers,
    },
  });

  if (!response.ok) {
    const error = await response.text().catch(() => "Unknown error");
    throw new Error(`GitHub API error (${response.status}): ${error}`);
  }

  return response;
}

/**
 * Get the authenticated user's information
 */
export async function getGitHubUser(accessToken: string): Promise<{
  login: string;
  id: number;
  avatar_url: string;
}> {
  const response = await githubFetch("/user", accessToken);
  return response.json();
}

/**
 * Check if the imagegate-images repository exists
 */
export async function repositoryExists(accessToken: string, username: string): Promise<boolean> {
  try {
    await githubFetch(`/repos/${username}/${REPO_NAME}`, accessToken);
    return true;
  } catch (error) {
    if ((error as Error).message.includes("404")) {
      return false;
    }
    throw error;
  }
}

/**
 * Create the imagegate-images repository
 */
export async function createRepository(accessToken: string): Promise<GitHubRepoResponse> {
  const response = await githubFetch("/user/repos", accessToken, {
    method: "POST",
    body: JSON.stringify({
      name: REPO_NAME,
      description: REPO_DESCRIPTION,
      private: false, // Public for free tier storage
      auto_init: true, // Initialize with README
    }),
  });

  return response.json();
}

/**
 * Ensure the image repository exists, create if not
 */
export async function ensureRepository(
  accessToken: string,
  username: string
): Promise<GitHubRepoResponse> {
  const exists = await repositoryExists(accessToken, username);

  if (exists) {
    // Get existing repo info
    const response = await githubFetch(`/repos/${username}/${REPO_NAME}`, accessToken);
    return response.json();
  }

  // Create new repository
  return createRepository(accessToken);
}

/**
 * Upload an image to GitHub repository
 */
export async function uploadImage(
  accessToken: string,
  username: string,
  filePath: string,
  imageBuffer: Buffer,
  commitMessage: string
): Promise<GitHubFileResponse> {
  const base64Content = imageBuffer.toString("base64");

  const response = await githubFetch(
    `/repos/${username}/${REPO_NAME}/contents/${filePath}`,
    accessToken,
    {
      method: "PUT",
      body: JSON.stringify({
        message: commitMessage,
        content: base64Content,
      }),
    }
  );

  return response.json();
}

/**
 * Check if a file exists in the repository
 */
export async function fileExists(
  accessToken: string,
  username: string,
  filePath: string
): Promise<{ exists: boolean; sha?: string }> {
  try {
    const response = await githubFetch(
      `/repos/${username}/${REPO_NAME}/contents/${filePath}`,
      accessToken
    );
    const data = await response.json();
    return { exists: true, sha: data.sha };
  } catch (error) {
    if ((error as Error).message.includes("404")) {
      return { exists: false };
    }
    throw error;
  }
}

/**
 * Get the raw content URL for an image
 */
export function getImageUrl(username: string, filePath: string): string {
  return `https://raw.githubusercontent.com/${username}/${REPO_NAME}/main/${filePath}`;
}

/**
 * Generate a file path for an image based on date
 */
export function generateImagePath(
  provider: string,
  model: string,
  timestamp: number
): string {
  const date = new Date(timestamp);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const filename = `${timestamp}_${provider}_${model.replace(/[^a-zA-Z0-9]/g, "_")}.png`;

  return `${year}/${month}/${day}/${filename}`;
}

/**
 * Delete a file from the repository
 */
export async function deleteFile(
  accessToken: string,
  username: string,
  filePath: string,
  sha: string,
  commitMessage: string
): Promise<void> {
  await githubFetch(
    `/repos/${username}/${REPO_NAME}/contents/${filePath}`,
    accessToken,
    {
      method: "DELETE",
      body: JSON.stringify({
        message: commitMessage,
        sha: sha,
      }),
    }
  );
}

/**
 * List files in a directory
 */
export async function listFiles(
  accessToken: string,
  username: string,
  directoryPath: string = ""
): Promise<Array<{
  name: string;
  path: string;
  sha: string;
  size: number;
  download_url: string;
}>> {
  const response = await githubFetch(
    `/repos/${username}/${REPO_NAME}/contents/${directoryPath}`,
    accessToken
  );
  return response.json();
}
